package com.sbigeneral.SECUREAPI.Entity;

public class SecurePolicyInfo {

	public String POLICY_NO;
	public String CUSTOMER_NAME;
	public String PRODUCT_NAME;
	public String AGREEMENT_CODE;
	public String INTERMEDIARY_CODE;
	public String INTERMEDIARY_NAME;
	public String SBI_BRANCH;
	public String SECONDARY_SALES_MANAGER_CODE;
	public String SECONDARY_SALES_MANAGER_NAME;
	public String EMAIL;
	public String MOBILE_NUMBER;
	public String getPOLICY_NO() {
		return POLICY_NO;
	}
	public SecurePolicyInfo() {
		super();
		// TODO Auto-generated constructor stub
	}
	public void setPOLICY_NO(String pOLICY_NO) {
		POLICY_NO = pOLICY_NO;
	}
	public String getCUSTOMER_NAME() {
		return CUSTOMER_NAME;
	}
	public void setCUSTOMER_NAME(String cUSTOMER_NAME) {
		CUSTOMER_NAME = cUSTOMER_NAME;
	}
	public String getPRODUCT_NAME() {
		return PRODUCT_NAME;
	}
	public void setPRODUCT_NAME(String pRODUCT_NAME) {
		PRODUCT_NAME = pRODUCT_NAME;
	}
	public String getAGREEMENT_CODE() {
		return AGREEMENT_CODE;
	}
	public void setAGREEMENT_CODE(String aGREEMENT_CODE) {
		AGREEMENT_CODE = aGREEMENT_CODE;
	}
	public String getINTERMEDIARY_CODE() {
		return INTERMEDIARY_CODE;
	}
	public void setINTERMEDIARY_CODE(String iNTERMEDIARY_CODE) {
		INTERMEDIARY_CODE = iNTERMEDIARY_CODE;
	}
	public String getINTERMEDIARY_NAME() {
		return INTERMEDIARY_NAME;
	}
	public void setINTERMEDIARY_NAME(String iNTERMEDIARY_NAME) {
		INTERMEDIARY_NAME = iNTERMEDIARY_NAME;
	}
	public String getSBI_BRANCH() {
		return SBI_BRANCH;
	}
	public void setSBI_BRANCH(String sBI_BRANCH) {
		SBI_BRANCH = sBI_BRANCH;
	}
	public String getSECONDARY_SALES_MANAGER_CODE() {
		return SECONDARY_SALES_MANAGER_CODE;
	}
	public void setSECONDARY_SALES_MANAGER_CODE(String sECONDARY_SALES_MANAGER_CODE) {
		SECONDARY_SALES_MANAGER_CODE = sECONDARY_SALES_MANAGER_CODE;
	}
	public String getSECONDARY_SALES_MANAGER_NAME() {
		return SECONDARY_SALES_MANAGER_NAME;
	}
	public void setSECONDARY_SALES_MANAGER_NAME(String sECONDARY_SALES_MANAGER_NAME) {
		SECONDARY_SALES_MANAGER_NAME = sECONDARY_SALES_MANAGER_NAME;
	}
	public String getEMAIL() {
		return EMAIL;
	}
	public void setEMAIL(String eMAIL) {
		EMAIL = eMAIL;
	}
	public String getMOBILE_NUMBER() {
		return MOBILE_NUMBER;
	}
	public void setMOBILE_NUMBER(String mOBILE_NUMBER) {
		MOBILE_NUMBER = mOBILE_NUMBER;
	}
	public SecurePolicyInfo(String pOLICY_NO, String cUSTOMER_NAME, String pRODUCT_NAME, String aGREEMENT_CODE,
			String iNTERMEDIARY_CODE, String iNTERMEDIARY_NAME, String sBI_BRANCH, String sECONDARY_SALES_MANAGER_CODE,
			String sECONDARY_SALES_MANAGER_NAME, String eMAIL, String mOBILE_NUMBER) {
		super();
		POLICY_NO = pOLICY_NO;
		CUSTOMER_NAME = cUSTOMER_NAME;
		PRODUCT_NAME = pRODUCT_NAME;
		AGREEMENT_CODE = aGREEMENT_CODE;
		INTERMEDIARY_CODE = iNTERMEDIARY_CODE;
		INTERMEDIARY_NAME = iNTERMEDIARY_NAME;
		SBI_BRANCH = sBI_BRANCH;
		SECONDARY_SALES_MANAGER_CODE = sECONDARY_SALES_MANAGER_CODE;
		SECONDARY_SALES_MANAGER_NAME = sECONDARY_SALES_MANAGER_NAME;
		EMAIL = eMAIL;
		MOBILE_NUMBER = mOBILE_NUMBER;
	}
	@Override
	public String toString() {
		return "SecurePolicyInfo [POLICY_NO=" + POLICY_NO + ", CUSTOMER_NAME=" + CUSTOMER_NAME + ", PRODUCT_NAME="
				+ PRODUCT_NAME + ", AGREEMENT_CODE=" + AGREEMENT_CODE + ", INTERMEDIARY_CODE=" + INTERMEDIARY_CODE
				+ ", INTERMEDIARY_NAME=" + INTERMEDIARY_NAME + ", SBI_BRANCH=" + SBI_BRANCH
				+ ", SECONDARY_SALES_MANAGER_CODE=" + SECONDARY_SALES_MANAGER_CODE + ", SECONDARY_SALES_MANAGER_NAME="
				+ SECONDARY_SALES_MANAGER_NAME + ", EMAIL=" + EMAIL + ", MOBILE_NUMBER=" + MOBILE_NUMBER + "]";
	}

	
}
