package com.sbigeneral.PINS.model;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.annotation.Resource;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.0.9 2018-02-01T18:57:08.961+05:30
 * Generated source version: 3.0.9
 * 
 */

@WebServiceClient(name = "DocSearchService", targetNamespace = "urn:in.sbigeneral.xml:corporate.edm.entity.atomic.DocumentSearch")

public class DocSearchService extends Service {
	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("urn:in.sbigeneral.xml:corporate.edm.entity.atomic.DocumentSearch",
			"DocSearchService");
	public final static QName DocumentumsearchRequestSoapHttpPort = new QName(
			"urn:in.sbigeneral.xml:corporate.edm.entity.atomic.DocumentSearch", "documentumsearchRequestSoapHttpPort");


	static {
		URL url = null;
		try {
			url = new URL("http://172.16.110.187:7300/Documentum/PS_DocSearch_V1.0?wsdl");
			
		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(DocSearchService.class.getName()).log(java.util.logging.Level.INFO,
					"Can not initialize the default wsdl from {0}", "/wsdl/policy.wsdl");
		}
		WSDL_LOCATION = url;
	}

	public DocSearchService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public DocSearchService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	/*public DocSearchService() {
		super(WSDL_LOCATION, SERVICE);
	}*/

	/**
	 *
	 * @return returns DocumentumsearchRequest
	 */
	@WebEndpoint(name = "documentumsearchRequestSoapHttpPort")
	public DocumentumsearchRequest getDocumentumsearchRequestSoapHttpPort() {
		return super.getPort(DocumentumsearchRequestSoapHttpPort, DocumentumsearchRequest.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns DocumentumsearchRequest
	 */
	@WebEndpoint(name = "documentumsearchRequestSoapHttpPort")
	public DocumentumsearchRequest getDocumentumsearchRequestSoapHttpPort(WebServiceFeature... features) {
		return super.getPort(DocumentumsearchRequestSoapHttpPort, DocumentumsearchRequest.class, features);
	}

}

