package com.sbigeneral.PINS.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.naming.spi.ObjectFactory;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * This class was generated by Apache CXF 3.0.9
 * 2018-02-01T18:57:08.956+05:30
 * Generated source version: 3.0.9
 * 
 */
@WebService(targetNamespace = "urn:in.sbigeneral.xml:corporate.edm.entity.atomic.DocumentSearch", name = "documentumsearchRequest")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DocumentumsearchRequest {
    @WebResult(name = "DocSearchResponse", targetNamespace = "urn:in.sbigeneral.xml:corporate.edm.entity.atomic.DocumentSearch", partName = "parameters")
    @WebMethod
    public DocSearchResponse documentumsearchRequestCreation(
        @WebParam(partName = "parameters", name = "DocSearchRequest", targetNamespace = "urn:in.sbigeneral.xml:corporate.edm.entity.atomic.DocumentSearch")
        DocSearchRequest parameters
    );
}
